-- bot.lua
-- Mineflayer bot lifecycle management (used when [Engine] = mineflayer).
--
-- Adapted from mcc.lua: same process-management skeleton (fd-close launch
-- wrapper, PID tracking with /proc cmdline guard, WaitForExit), but the launch
-- command targets bot/index.js (Node) and the signal ladder is simplified to
-- two levels because Node exits on SIGTERM by default.

-- Exposed globals (used by main.lua, tools.lua, Info.lua):
--   StartBot(opts)          -> (ok, msg)   launch the mineflayer bot
--   StopBot()               -> (ok, msg)   terminate the bot
--   RestartBot(opts)        -> (ok, msg)   stop then start
--   GetBotStatus()          -> table       status snapshot
--   HandleConsoleBot(a_Split) -> (true, msg)

local g_BotPid = nil

----------------------------------------------------------------------
-- Process helpers
----------------------------------------------------------------------

local function IsPidAlive(a_Pid)
	if not a_Pid then
		return false
	end
	local ok = os.execute("kill -0 " .. a_Pid .. " 2>/dev/null")
	return (ok == 0) or (ok == true)
end

-- Whether the PID is alive AND still the bot process we launched (cmdline
-- guard against PID reuse).
local function IsBotProcess(a_Pid)
	if not IsPidAlive(a_Pid) then
		return false
	end
	local f = io.popen("tr '\0' ' ' < /proc/" .. a_Pid .. "/cmdline 2>/dev/null")
	local cmdline = ""
	if f then
		cmdline = f:read("*a") or ""
		f:close()
	end
	if cmdline == "" then
		return true
	end
	local cfg = g_MCPConfig.Bot
	-- Match the bot entry script path (fall back to a bare "bot/index.js").
	return (cfg.BotDir ~= "") and (
		(cmdline:find(cfg.BotDir .. "/index.js", 1, true) ~= nil) or
		(cmdline:find("bot/index.js", 1, true) ~= nil)
	)
end

local function WaitForExit(a_Pid, a_Seconds, a_Sleep)
	local deadline = (a_Seconds / a_Sleep) + 0.5
	for _ = 1, math.floor(deadline) do
		if not IsPidAlive(a_Pid) then
			return true
		end
		os.execute("sleep " .. tostring(a_Sleep))
	end
	return not IsPidAlive(a_Pid)
end

----------------------------------------------------------------------
-- Command construction
----------------------------------------------------------------------

local function BuildBotCommand(a_Opts)
	a_Opts = a_Opts or {}
	local cfg = g_MCPConfig.Bot
	local nodePath = cfg.NodePath
	local botDir = cfg.BotDir
	-- Defense in depth: config.lua already resolves defaults ("node" for the
	-- executable, plugin-folder-relative for BotDir), but keep sane fallbacks
	-- in case this module is used without LoadMCPConfig.
	if nodePath == "" then
		nodePath = "node"
		LOG("[MCP] Bot.NodePath empty, using 'node' from PATH")
	end
	if botDir == "" then
		botDir = g_PluginFolder .. "/bot"
		LOG("[MCP] Bot.BotDir empty, defaulting to plugin folder /bot")
	end

	local username = cfg.Username
	local doRandom = cfg.RandomUsername
	if a_Opts.random_name == "force" then
		doRandom = true
	elseif a_Opts.random_name == "fixed" then
		doRandom = false
	end
	if doRandom then
		local suffix = tostring(math.random(1000, 9999))
		username = cfg.Username .. "_" .. suffix
		LOG("[MCP] Using randomized bot username: " .. username)
	end

	local tmpIni = g_PluginFolder .. "/bot_temp.ini"
	local f = io.open(tmpIni, "w")
	if not f then
		return nil, "Cannot write " .. tmpIni
	end
	f:write("; Generated by bot.lua - mcpserver-bot config\n")
	f:write("[Bot]\n")
	f:write("Host = " .. cfg.ServerHost .. "\n")
	f:write("Port = " .. cfg.ServerPort .. "\n")
	f:write("Username = " .. username .. "\n")
	f:write("RandomUsername = " .. tostring(doRandom) .. "\n")
	f:write("Version = " .. cfg.MinecraftVersion .. "\n")
	f:write("McpBind = 127.0.0.1\n")
	f:write("McpPort = " .. cfg.McpPort .. "\n")
	f:write("ReconnectAttempts = 5\n")
	f:close()

	return '"' .. nodePath .. '" "' .. botDir .. '/index.js" --config "' .. tmpIni .. '"'
end

----------------------------------------------------------------------
-- Lifecycle
----------------------------------------------------------------------

function StartBot(a_Opts)
	a_Opts = a_Opts or {}
	if g_BotPid and a_Opts.random_name == "force" then
		LOG("[MCP] Force launch requested, stopping existing bot (PID " .. g_BotPid .. ")")
		StopBot()
	end
	if g_BotPid and not IsBotProcess(g_BotPid) then
		LOGWARNING("[MCP] Stale bot PID " .. g_BotPid .. " is no longer running, clearing it")
		g_BotPid = nil
	end
	if g_BotPid then
		LOG("[MCP] Bot already running (PID " .. g_BotPid .. ")")
		return false, "already running"
	end
	local cfg = g_MCPConfig.Bot
	if not cfg.Enabled then
		LOG("[MCP] Bot integration is disabled in config")
		return false, "Bot disabled in config"
	end
	local cmd, err = BuildBotCommand(a_Opts)
	if not cmd then
		LOGWARNING("[MCP] Cannot start bot: " .. err)
		return false, err
	end
	local logFile = g_PluginFolder .. "/bot_output.log"
	local fullCmd = '{ for fd in /proc/self/fd/*; do n=' .. '${fd##*/}' .. '; case "$n" in 0|1|2) ;; *) eval "exec $n>&-" 2>/dev/null ;; esac; done; exec ' .. cmd .. ' > "' .. logFile .. '" 2>&1; } & echo $!'
	LOG("[MCP] Starting bot: " .. cmd)
	local f = io.popen(fullCmd)
	if not f then
		LOGWARNING("[MCP] io.popen failed for bot")
		return false, "io.popen failed"
	end
	local pidStr = f:read("*a")
	f:close()
	pidStr = pidStr:match("^(%d+)")
	if not pidStr then
		LOGWARNING("[MCP] Could not read bot PID")
		return false, "could not read PID"
	end
	g_BotPid = tonumber(pidStr)
	LOG("[MCP] Bot started with PID " .. g_BotPid .. ", output -> " .. logFile)
	return true, "Bot started (PID " .. g_BotPid .. ")"
end

-- Signal ladder: Node exits on SIGTERM by default; SIGKILL is the fallback.
local g_StopLadder = {
	{ "SIGTERM", "kill %d",       1.5 },
	{ "SIGKILL", "kill -9 %d",    1.0 },
}

function StopBot()
	if not g_BotPid then
		return false, "Bot not running"
	end
	local pid = g_BotPid
	LOG("[MCP] Stopping bot (PID " .. pid .. ")")
	if IsBotProcess(pid) then
		local exited = false
		for i, step in ipairs(g_StopLadder) do
			os.execute(string.format(step[2], pid) .. " 2>/dev/null")
			if WaitForExit(pid, step[3], 0.1) then
				exited = true
				break
			end
			if i < #g_StopLadder then
				LOGWARNING("[MCP] bot PID " .. pid .. " ignored " .. step[1] .. ", escalating to " .. g_StopLadder[i + 1][1])
			else
				LOGWARNING("[MCP] bot PID " .. pid .. " still present after SIGKILL (zombie?); continuing")
			end
		end
	else
		LOGWARNING("[MCP] bot PID " .. pid .. " was not running anymore")
	end
	g_BotPid = nil
	LOG("[MCP] Bot stopped")
	return true, "Bot stopped"
end

function RestartBot(a_Opts)
	if g_BotPid then
		StopBot()
	end
	return StartBot(a_Opts)
end

function GetBotStatus()
	local cfg = g_MCPConfig.Bot
	if g_BotPid and not IsBotProcess(g_BotPid) then
		g_BotPid = nil
	end
	local status = {
		enabled         = cfg.Enabled,
		autostart       = cfg.AutoStart,
		running         = g_BotPid ~= nil,
		pid             = g_BotPid,
		username        = cfg.Username,
		random_username = cfg.RandomUsername,
		version         = cfg.MinecraftVersion,
		mcp_port        = cfg.McpPort,
	}
	return status
end

----------------------------------------------------------------------
-- Console command handler
----------------------------------------------------------------------

local function ParseRandomNameFlag(a_Split)
	for i = 3, #a_Split do
		local tok = a_Split[i]:lower()
		if tok == "random" then
			return "force"
		elseif tok == "norandom" or tok == "fixed" then
			return "fixed"
		end
	end
	return nil
end

function HandleConsoleBot(a_Split)
	local sub = a_Split[2] or "status"
	if sub == "start" then
		local ok, msg = StartBot({ random_name = ParseRandomNameFlag(a_Split) })
		return true, msg
	elseif sub == "stop" then
		local ok, msg = StopBot()
		return true, msg
	elseif sub == "restart" then
		local ok, msg = RestartBot({ random_name = ParseRandomNameFlag(a_Split) })
		return true, msg
	elseif sub == "status" then
		local s = GetBotStatus()
		if s.running then
			return true, "Bot is running (PID " .. tostring(s.pid) .. ", user " .. tostring(s.username) .. ", mcp_port " .. tostring(s.mcp_port) .. ")"
		end
		if s.enabled then
			return true, "Bot is enabled but not running"
		end
		return true, "Bot is disabled in config"
	end
	return true, "Usage: bot <start|stop|restart|status> [random|norandom]"
end
